#!/bin/bash

set -e

exec 3>&1
exec 1>&2

set +x

payload=$(mktemp /tmp/resource-check.XXXXXX)

cat > "${payload}" <&0

base_uri="https://willem.habitat.sh/v1/depot"
origin="$(jq -r '.source.origin' < "${payload}")"
name="$(jq -r '.source.name' < "${payload}")"
version="$(jq -r '.source.version // ""' < "${payload}")"
if [[ ${version} != "" ]]; then
  version="/${version}"
fi
channel="$(jq -r '.source.channel // ""' < "${payload}")"
if [[ ${channel} != "" ]]; then
  channel="unstable"
fi

latest_version="$(jq -r '.version.pkg' < "${payload}")"

if [[ ${latest_version} == 'null' ]]; then
  curl "${base_uri}/channels/${origin}/${channel}/pkgs/${name}${version}/latest" 2>/dev/null | \
    jq '.ident | [ .origin, .name, .version, .release ] | [{pkg: join("/")}]' >&3
else
  curl "${base_uri}/channels/${origin}/${channel}/pkgs/${name}${version}" 2>/dev/null | \
    jq --arg current ${latest_version} '[ .package_list[] | { pkg: [ .origin, .name, .version, .release ] | join("/") | select(. >= $current) } ]' >&3
fi
