#!/bin/bash

set +x

payload=$(mktemp /tmp/resource-in.XXXXXX)

cat > "${payload}" <&0

origin="$(jq -r '.source.origin' < "${payload}")"
name="$(jq -r '.source.name' < "${payload}")"

export HAB_ORIGIN=${origin}
HAB_ORIGIN_KEY="$(jq -r '.source.origin_key' < "${payload}")"

cat <<EOF | hab origin key import
${HAB_ORIGIN_KEY}
EOF

cd $1

file=$(ls *.hart)
pkg="$(echo ${pkg/-x86_64-linux.hart} | sed 's#-#/#g')"

hab pkg upload $file

jq -n --arg pkg "${pkg}" '{version: { pkg: $pkg }}'
