#!/bin/bash

set -e

exec 3>&1
exec 1>&2

set +x

payload=$(mktemp /tmp/resource-in.XXXXXX)
keys_cache=$(mktemp /tmp/hab_cache_keys_path.XXXXXX)
trap "rm -f ${keys_cahce}" INT QUIT TERM EXIT
export HAB_CACHE_KEYS_PATH=${keys_cache}


cat > "${payload}" <&0

origin="$(jq -r '.source.origin' < "${payload}")"
name="$(jq -r '.source.name' < "${payload}")"
channel="$(jq -r '.params.channel // ""' < "${payload}")"
if [[ ${channel} = "" ]]; then
  channel="$(jq -r '.source.channel // "unstable"' < "${payload}")"
fi

export HAB_ORIGIN=${origin}
export HAB_AUTH_TOKEN="$(jq -r '.source.auth_token' < "${payload}")"

hab origin key download ${origin}

result="$(jq -r '.params.result' < "${payload}")"
cd "${1}/${result}"

file=$(ls *.hart)
pkg=${file/-x86_64-linux.hart}
pkg=${pkg#$origin-$name-}
pkg="${origin}/${name}/$(echo ${pkg} | sed "s#-#/#g")"

hab pkg upload -c ${channel} $file

jq -n --arg pkg "${pkg}" '{version: { pkg: $pkg }}' >&3
